Candidate: CVE-2024-5629
PublicDate: 2024-06-05 15:15:00 UTC
References:
 https://www.cve.org/CVERecord?id=CVE-2024-5629
 https://jira.mongodb.org/browse/PYTHON-4305
Description:
 An out-of-bounds read in the 'bson' module of PyMongo 4.6.2 or earlier
 allows deserialization of malformed BSON provided by a Server to raise an
 exception which may contain arbitrary application memory.
Ubuntu-Description:
Notes:
Mitigation:
Bugs:
Priority: medium
Discovered-by:
Assigned-to: leosilva
CVSS:
 nvd: CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:N/A:H [8.1 HIGH]


Patches_pymongo:
 upstream: https://github.com/mongodb/mongo-python-driver/commit/56b6b6dbc267d365d97c037082369dabf37405d2 (v4.6)
 upstream: https://github.com/mongodb/mongo-python-driver/commit/372b5d68d5a57ccc43b33407cd23f0bc79d99283 (v4.8)
upstream_pymongo: needs-triage
trusty/esm_pymongo: needs-triage
esm-infra-legacy/trusty_pymongo: needs-triage
esm-infra/xenial_pymongo: needs-triage
esm-infra/bionic_pymongo: needs-triage
focal_pymongo: needs-triage
jammy_pymongo: needs-triage
mantic_pymongo: needs-triage
noble_pymongo: needs-triage
devel_pymongo: needs-triage
